---

- name: "[setting site-name related vars]"
  set_fact:
    wp_table_prefix: "{{ wordpress_db_table_prefix | default('wp_'+wordpress_site_name+'_') }}"
  when: "wordpress_site_name != 'wordpress'"

- name: "[setting default site-name vars]"
  set_fact:
    wp_table_prefix: "{{ wordpress_db_table_prefix | default('wp_') }}"
  when: "wordpress_site_name == 'wordpress'"

- name: "[setting db vars]"
  set_fact:
    wp_db_host: "{{ wordpress_db_host | default('localhost') }}"
    wp_db_name: "{{ wordpress_db_name | default('wp_database') }}"
    wp_db_user: "{{ wordpress_db_user | default('wp_user') }}"
    wp_db_password: "{{ wordpress_db_user_password | default('wp_user_password') }}"
    wp_lang: "{{ wordpress_language | default('en_US') }}"
    wp_debug: "{{ wordpress_debug | default(false) }}"
  no_log: true

- name: "[disabling letsencrypt]"
  set_fact:
    wordpress_request_https_cert: false
- name: "[enabling letsencrypt]"
  set_fact:
    wordpress_request_https_cert: true
  when: "wordpress_letsencrypt_email is defined and wordpress_letsencrypt_email and wordpress_letsencrypt_email not in ['false', 'False', 'no', 'No', 'none', 'None']"

- name: "[setting https related stuff]"
  set_fact:
    wordpress_letsencrypt_cert_domains:
      - "{{ wordpress_domain }}"
  when: wordpress_request_https_cert
